#!/usr/bin/env bash
#Install nginx on your web-01 while nginx listens on port 80


sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > sudo var/www/html/index.html
sudo service nginx start
