#!/usr/bin/env bash
# Configure nginx in a new Ubuntu machine with a permanent redirect

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo -e "Hello World!" | sudo tee /var/www/html/index.html >/dev/null
sudo tee /etc/nginx/sites-available/default >/dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF
sudo service nginx restart
