#!/usr/bin/env bash
# Configure a new Ubuntu machine by installing Nginx and setting up a custom 404 page

# Function to display a message
log_message() {
    echo -e "\n$1\n"
}

log_message "Updating and installing Nginx..."
sudo apt-get update -qq
sudo apt-get install -y nginx

log_message "Setting up minor configurations..."

# Start Nginx service
sudo service nginx start

# Allow Nginx through firewall
sudo ufw allow 'Nginx HTTP'

# Give ownership of website files to current user
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html

# Backup default index file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bak

# Create new index file with "Hello World!"
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Set up a redirection to a YouTube video
sudo sed -i '/server {/a \
    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Set up a custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sudo sed -i '/server {/a \
    error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

echo -e "\nSetup completed.\n"
