#!/usr/bin/env bash
#Install nginx on your web-01 while nginx listens on port 80


sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo -e "Hello World!\n" | sudo tee /var/www/html/index.html >/dev/null
sudo service nginx start
