#!/usr/bin/env bash
# Configuring HAProxy load balancer

sudo apt-get update
sudo apt-get -y install haproxy

config="listen load-balancer
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 409581-web-01 <web-01-54.160.79.156>:80 check
	server 409581-web-02 <web-02-34.207.64.145>:80 check
	server 409581-lb-01 <lb-01-54.197.47.183>:80 check"

echo -e "$config" | sudo tee -a /etc/haproxy/haproxy.cfg >/dev/null

sudo systemctl restart haproxy
