#!/usr/bin/env bash
# Installs and setup haproxy
# Install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Enable HAProxy service
echo "ENABLED=1" > /etc/default/haproxy

# Append configuration to haproxy.cfg
echo "
frontend naouwa.tech
        bind *:80
        mode http
        default_backend servers

backend servers
        balance roundrobin
        server 409581-web-01 54.160.79.156:80 check
        server 409581-web-02 34.207.64.145:80 check" >> /etc/haproxy/haproxy.cfg

sudo ufw allow 80/tcp
# Start HAProxy service
sudo service haproxy restart
